site_name: Hanami
site_author: Tobias Anker
site_url: https://docs.hanami-ai.com

repo_name: kitsudaiki/Hanami
repo_url: https://github.com/kitsudaiki/Hanami

theme:
  name: material
  language: en
  logo: img/hanami-logo-pink.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.top
    - content.code.annotate 
    - content.tabs.link

nav:
  - Home:
    - index.md
    - home/license.md
    - home/CHANGELOG.md
  - Usage:
    - api/rest_api_documentation.md
    - api/sdk_library.md
    - api/cluster_template.md
    - api/websocket_workflow.md
  - How To:
    - how_to/installation.md
    - how_to/development.md
    - how_to/dashboard.md
  - Inner workings:
    - inner_workings/core.md
    - inner_workings/input_processing.md
    - inner_workings/monitoring.md
    - inner_workings/storage.md
    - inner_workings/user_and_projects.md
    - Configs:
      - inner_workings/config.md
      - inner_workings/db.md
    - Libraries (Archive):
      - inner_workings/libraries/hanami_args.md
      - inner_workings/libraries/hanami_common.md
      - inner_workings/libraries/hanami_config.md
      - inner_workings/libraries/hanami_cpu.md
      - inner_workings/libraries/hanami_crypto.md
      - inner_workings/libraries/hanami_ini.md
      - inner_workings/libraries/hanami_obj.md
      - inner_workings/libraries/hanami_opencl.md
      - inner_workings/libraries/hanami_sqlite.md
  - Other:
    - other/dependencies.md
    - other/code_styling.md
    - other/git_workflow.md
    - other/glossar.md

plugins:
    - swagger-ui-tag
    - search
    - drawio-exporter:
        # Diagrams are cached to speed up site generation. The default path is
        # drawio-exporter, relative to the documentation directory.
        cache_dir: 'drawio-exporter'
        # Path to the Draw.io executable:
        #   * drawio on Linux
        #   * draw.io on macOS
        #   * or draw.io.exe on Windows
        # We'll look for it on your system's PATH, then default installation
        # paths. If we can't find it we'll warn you.
        drawio_executable: null
        # Additional Draw.io CLI args
        drawio_args: []
        # Output format (see draw.io --help | grep format)
        format: svg
        # Embed format
        #   * The default is to embed via the <img> tag, only rewriting the
        #     value of the src attribute.
        #   * Consider <object type="image/svg+xml" data="{img_src}"></object>
        #     to enable interactive elements (like hyperlinks) in SVGs.
        embed_format: '{img_open}{img_src}{img_close}'
        # Glob pattern for matching source files
        sources: '*.drawio'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 

extra_css:
  - stylesheets/extra.css

copyright: all rights reserved; 2022-2024 Tobias Anker

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kitsudaiki
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/tobiasanker42
