---
- name: Install nginx
  become: yes
  ansible.builtin.apt: 
    name: [ 'nginx' ]
    state: latest 
    update_cache: yes


- name: Create nginx-config from template
  become: yes
  template:
    src: hanami_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/hanami.conf
    mode: 0777


- name: Create private key for self-signed certificate
  community.crypto.openssl_privatekey:
    path: "{{ ssl_key_path }}"
    type: RSA

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ ssl_cert_path }}"
    privatekey_path: "{{ ssl_key_path }}"
    provider: selfsigned


- name: Restart nginx to apply config
  become: yes
  ansible.builtin.service:
    name: nginx
    state: restarted
