apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hanami-ingress
spec:
  tls:
    - hosts:
        - local-hanami
      secretName: hanami-selfsigned-secret
  rules:
  - host: local-hanami
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: hanami-service
              port:
                number: 1337
