apiVersion: v1
metadata:
  name: hanami-config
data:
  hanami.conf: |+
    [DEFAULT]
    debug = True
    log_path = "/var/log"
    database = "/etc/hanami/hanami_db"
    use_cuda = false

    [storage]
    data_set_location = "/etc/hanami/train_data"
    checkpoint_location = "/etc/hanami/checkpoint"

    [auth]
    policies = "/etc/hanami/policies"
    token_key_path = "/etc/hanami/token_key"
    token_expire_time = {{ .Values.token.expire_time }}

    [http]
    enable = True
    ip = {{ .Values.api.ip }}
    dashboard_files = "/etc/Hanami-Dashboard/src"
    port = {{ .Values.api.port }}
    enable_dashboard = True

kind: ConfigMap
