apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hanami-selfsigned-cert
spec:
  secretName: hanami-selfsigned-secret
  issuerRef:
    name: selfsigned-issuer
  dnsNames:
    - local-hanami

