apiVersion: v1
kind: Service
metadata:
  name: hanami-service
  labels:
    run: hanami-project
spec:
  selector:
    app: hanami
  ports:
    - name: input
      protocol: TCP
      port: 1337
      targetPort: 1337
