name: build-and-test

on: [push, create]

env:
  REGISTRY_IMAGE: kitsudaiki/hanami

jobs:
  clang-format-check:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run check
        run: earthly --ci +clang-format

  cpp-check:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run check
        run: earthly --ci +cppcheck

  ansible-lint:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run check
        run: earthly --ci +ansible-lint

  flake8-check:
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - uses: actions/checkout@v4
      - name: Run check
        run: earthly --ci +flake8


  build:
    name: "Compile code"
    needs: [ cpp-check, clang-format-check, ansible-lint, flake8-check ]
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 1
    steps:
      - uses: earthly/actions-setup@v1
        with:
          version: v0.8.0
      - name: Checkout repository
        run: |
          # use manually clone, because with the "actions/checkout@v3" action the name of the
          # branch can not be read by the git commands, which is necessary for the build-script
          git clone https://github.com/kitsudaiki/${GITHUB_REPOSITORY#*/}.git
          cd ${GITHUB_REPOSITORY#*/}
          git checkout ${GITHUB_REF#refs/heads/}
          git submodule init
          git submodule update --recursive
      - name: Compile code
        run: |
          cd ${GITHUB_REPOSITORY#*/}
          earthly --artifact +compile-code/tmp/Hanami ./builds/binaries
      - name: Copy files
        run: |
          mkdir /tmp/build_result
          cd ${GITHUB_REPOSITORY#*/}
          cp -r builds/binaries/* /tmp/build_result/
      - name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: result
          path: /tmp/build_result

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    name: "Unit-Tests"
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y openssl libuuid1 libcrypto++8 libsqlite3-0 libprotobuf23 libboost1.74 libcudart11.0
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: result
          path: /tmp/build_result
      - name: "Check target-directory"
        run: ls -l /tmp/build_result
      - name: "Run test: hanami_common"
        run: |
          chmod +x /tmp/build_result/hanami_common_unit_tests
          /tmp/build_result/hanami_common_unit_tests
      - name: "Run test: hanami_config"
        run: |
          chmod +x /tmp/build_result/hanami_config_unit_tests
          /tmp/build_result/hanami_config_unit_tests
      - name: "Run test: hanami_crypto"
        run: |
          chmod +x /tmp/build_result/hanami_crypto_unit_tests
          /tmp/build_result/hanami_crypto_unit_tests
      - name: "Run test: hanami_ini"
        run: |
          chmod +x /tmp/build_result/hanami_ini_unit_tests
          /tmp/build_result/hanami_ini_unit_tests
      - name: "Run test: hanami_sqlite"
        run: |
          chmod +x /tmp/build_result/hanami_sqlite_unit_tests
          /tmp/build_result/hanami_sqlite_unit_tests
      - name: "Run test: hanami_cluster_parser"
        run: |
          chmod +x /tmp/build_result/hanami_cluster_parser_unit_tests
          /tmp/build_result/hanami_cluster_parser_unit_tests
      - name: "Run test: hanami_policies"
        run: |
          chmod +x /tmp/build_result/hanami_policies_unit_tests
          /tmp/build_result/hanami_policies_unit_tests
      - name: "Run test: hanami_args"
        run: |
          chmod +x  /tmp/build_result/hanami_args_unit_tests
          /tmp/build_result/hanami_args_unit_tests

  memory_leak_tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    name: "Memory-Leak-Tests"
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y openssl libuuid1 libcrypto++8 libsqlite3-0 libprotobuf23 libboost1.74 libcudart11.0
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: result
          path: /tmp/build_result
      - name: "Check target-directory"
        run: ls -l /tmp/build_result
      - name: "Run test: hanami_common"
        run: |
          chmod +x /tmp/build_result/hanami_common_memory_leak_tests
          /tmp/build_result/hanami_common_memory_leak_tests
      - name: "Run test: hanami_cluster_parser"
        run: |
          chmod +x /tmp/build_result/hanami_cluster_parser_memory_leak_tests
          /tmp/build_result/hanami_cluster_parser_memory_leak_tests


  functional_tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
    name: "Functional-Tests"
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y openssl libuuid1 libcrypto++8 libsqlite3-0 libprotobuf23 libboost1.74 libcudart11.0
      - name: Get artifact
        uses: actions/download-artifact@v4
        with:
          name: result
          path: /tmp/build_result
      - name: "Check target-directory"
        run: ls -l /tmp/build_result
      - name: "Run test: hanami_config"
        run: |
          chmod +x /tmp/build_result/hanami_config_functional_tests
          /tmp/build_result/hanami_config_functional_tests
      # - name: "Run test: hanami_obj"
      #   run: |
      #     chmod +x /tmp/build_result/libraries/hanami_obj/tests/functional_tests/functional_tests
      #     /tmp/build_result/libraries/hanami_obj/tests/functional_tests/functional_tests
      - name: "Run test: hanami_database"
        run: |
          chmod +x /tmp/build_result/hanami_database_functional_tests
          /tmp/build_result/hanami_database_functional_tests
      # - name: "Run test: hanami_network"
      #   run: |
      #     chmod +x /tmp/build_result/libraries/hanami_network/tests/functional_tests/functional_tests
      #     /tmp/build_result/libraries/hanami_network/tests/functional_tests/functional_tests

  cleanup:
    needs: [ unit_tests, memory_leak_tests, functional_tests ]
    runs-on: ubuntu-latest
    name: cleanup-job
    steps:
      - name: "Delete artifacts"
        uses: geekyeggo/delete-artifact@v4
        with:
          name: result

  docker_build:
    name: "Build Docker-images"
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' || github.event_name == 'create' && startsWith(github.ref, 'refs/tags/') }}
    needs: [ unit_tests, memory_leak_tests, functional_tests ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV          
      - name: "Checkout repository"
        run: |
          # use manually clone, because with the "actions/checkout@v3" action the name of the
          # branch can not be read by the git commands, which is necessary for the build-script
          git clone https://github.com/kitsudaiki/${GITHUB_REPOSITORY#*/}.git
          cd ${GITHUB_REPOSITORY#*/}
          git checkout ${GITHUB_REF#refs/heads/}
          git submodule init
          git submodule update --recursive
      - name: "Install packages"
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-15 gcc g++ make cmake bison flex git ssh libssl-dev libcrypto++-dev libboost1.74-dev uuid-dev libsqlite3-dev protobuf-compiler nvidia-cuda-toolkit nano
      - name: "Build project"
        run:  |
          cd ${GITHUB_REPOSITORY#*/}
          cmake -DCMAKE_BUILD_TYPE=Release "$PARENT_DIR/Hanami"
          make -j8
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: check location
        run: |
          pwd
          cd Hanami
          ls -l
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./Hanami
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"          
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1
  docker_merge:
    name: "Merge and push Docker-image"
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' || github.event_name == 'create' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/develop'
    needs:
      - docker_build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)          
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}       
